
using System.Collections.Generic;

namespace RWD.Toolbox.Strings.Address.Models
{
   /// <summary>
   /// Set of Codes Needed for Address Control to Function
   /// </summary>
   public sealed class MasterCodeSet : IMasterCodeSet
   {
      /// <inheritdoc/>
      public List<DirectionalCode> DirectionalCodes
      {
         get { return DirectionalTable; }
      }

      /// <inheritdoc/>
      public List<DirectionalAlias> DirectionalAliases
      {
         get { return DirectionalAliasesTable; }
      }

      /// <inheritdoc/>
      public List<StreetSuffixCode> StreetSuffixCodes
      {
         get { return StreetSuffixTable; }
      }

      /// <inheritdoc/>
      public List<StreetSuffixAlias> StreetSuffixAliases
      {
         get { return StreetSuffixAliasTable; }
      }

      /// <inheritdoc/>
      public List<StreetSecondaryUnitCode> StreetSecondaryUnitCodes
      {
         get { return StreetSecondaryUnitTable; }
      }

      /// <inheritdoc/>
      public List<StreetSecondaryUnitAlias> StreetSecondaryUnitAliases
      {
         get { return StreetSecondaryUnitAliasTable; }
      }

      /// <inheritdoc/>
      public List<StateCode> StateCodes
      {
         get { return StateTable; }
      }

      /// <inheritdoc/>
      public List<StateAlias> StateAliases
      {
         get { return StateAbrvLegacyTable; }
      }

      /// <inheritdoc/>
      public List<CountryCode> CountryCodes
      {
         get { return CountryTable; }
      }

      /// <inheritdoc/>
      public List<CountryAlias> CountryAliases
      {
         get { return CountryAliasTable; }
      }


      private readonly List<DirectionalCode> DirectionalTable = new List<DirectionalCode>(new DirectionalCode[] {
        new DirectionalCode() { Id = 1, Code = "N", Description = "NORTH" },
        new DirectionalCode() { Id = 2, Code = "NE", Description = "NORTHEAST" },
        new DirectionalCode() { Id = 3, Code = "E", Description = "EAST" },
        new DirectionalCode() { Id = 4, Code = "SE", Description = "SOUTHEAST" },
        new DirectionalCode() { Id = 5, Code = "S", Description = "SOUTH" },
        new DirectionalCode() { Id = 6, Code = "SW", Description = "SOUTHWEST" },
        new DirectionalCode() { Id = 7, Code = "W", Description = "WEST" },
        new DirectionalCode() { Id = 8, Code = "NW", Description = "NORTHWEST" }
    });

      private readonly List<DirectionalAlias> DirectionalAliasesTable = new List<DirectionalAlias>(new DirectionalAlias[] {
        new DirectionalAlias() { Id = 1, AliasName = "N.", ForeignId = 1 },
        new DirectionalAlias() { Id = 2, AliasName = "N.E.", ForeignId = 2 },
        new DirectionalAlias() { Id = 3, AliasName = "E.", ForeignId = 3 },
        new DirectionalAlias() { Id = 4, AliasName = "S.E.", ForeignId = 4 },
        new DirectionalAlias() { Id = 5, AliasName = "S.", ForeignId = 5 },
        new DirectionalAlias() { Id = 6, AliasName = "S.W.", ForeignId = 6 },
        new DirectionalAlias() { Id = 7, AliasName = "W.", ForeignId = 7 },
        new DirectionalAlias() { Id = 8, AliasName = "N.W.", ForeignId = 8 }
    });

      private readonly List<StreetSuffixCode> StreetSuffixTable = new List<StreetSuffixCode>(new StreetSuffixCode[] {
        new StreetSuffixCode() { Id = 1, Code = "ALY", Description = "ALLEY" },
        new StreetSuffixCode() { Id = 2, Code = "ANX", Description = "ANEX" },
        new StreetSuffixCode() { Id = 3, Code = "ARC", Description = "ARCADE" },
        new StreetSuffixCode() { Id = 4, Code = "AVE", Description = "AVENUE" },
        new StreetSuffixCode() { Id = 5, Code = "BYU", Description = "BAYOU" },
        new StreetSuffixCode() { Id = 6, Code = "BCH", Description = "BEACH" },
        new StreetSuffixCode() { Id = 7, Code = "BND", Description = "BEND" },
        new StreetSuffixCode() { Id = 8, Code = "BLF", Description = "BLUFF" },
        new StreetSuffixCode() { Id = 9, Code = "BLFS", Description = "BLUFFS" },
        new StreetSuffixCode() { Id = 10, Code = "BTM", Description = "BOTTOM" },
        new StreetSuffixCode() { Id = 11, Code = "BLVD", Description = "BOULEVARD" },
        new StreetSuffixCode() { Id = 12, Code = "BR", Description = "BRANCH" },
        new StreetSuffixCode() { Id = 13, Code = "BRG", Description = "BRIDGE" },
        new StreetSuffixCode() { Id = 14, Code = "BRK", Description = "BROOK" },
        new StreetSuffixCode() { Id = 15, Code = "BRKS", Description = "BROOKS" },
        new StreetSuffixCode() { Id = 16, Code = "BG", Description = "BURG" },
        new StreetSuffixCode() { Id = 17, Code = "BGS", Description = "BURGS" },
        new StreetSuffixCode() { Id = 18, Code = "BYP", Description = "BYPASS" },
        new StreetSuffixCode() { Id = 19, Code = "CP", Description = "CAMP" },
        new StreetSuffixCode() { Id = 20, Code = "CYN", Description = "CANYON" },
        new StreetSuffixCode() { Id = 21, Code = "CPE", Description = "CAPE" },
        new StreetSuffixCode() { Id = 22, Code = "CSWY", Description = "CAUSEWAY" },
        new StreetSuffixCode() { Id = 23, Code = "CTR", Description = "CENTER" },
        new StreetSuffixCode() { Id = 24, Code = "CTRS", Description = "CENTERS" },
        new StreetSuffixCode() { Id = 25, Code = "CIR", Description = "CIRCLE" },
        new StreetSuffixCode() { Id = 26, Code = "CIRS", Description = "CIRCLES" },
        new StreetSuffixCode() { Id = 27, Code = "CLF", Description = "CLIFF" },
        new StreetSuffixCode() { Id = 28, Code = "CLFS", Description = "CLIFFS" },
        new StreetSuffixCode() { Id = 29, Code = "CLB", Description = "CLUB" },
        new StreetSuffixCode() { Id = 30, Code = "CMN", Description = "COMMON" },
        new StreetSuffixCode() { Id = 31, Code = "CMNS", Description = "COMMONS" },
        new StreetSuffixCode() { Id = 32, Code = "COR", Description = "CORNER" },
        new StreetSuffixCode() { Id = 33, Code = "CORS", Description = "CORNERS" },
        new StreetSuffixCode() { Id = 34, Code = "CRSE", Description = "COURSE" },
        new StreetSuffixCode() { Id = 35, Code = "CT", Description = "COURT" },
        new StreetSuffixCode() { Id = 36, Code = "CTS", Description = "COURTS" },
        new StreetSuffixCode() { Id = 37, Code = "CV", Description = "COVE" },
        new StreetSuffixCode() { Id = 38, Code = "CVS", Description = "COVES" },
        new StreetSuffixCode() { Id = 39, Code = "CRK", Description = "CREEK" },
        new StreetSuffixCode() { Id = 40, Code = "CRES", Description = "CRESCENT" },
        new StreetSuffixCode() { Id = 41, Code = "CRST", Description = "CREST" },
        new StreetSuffixCode() { Id = 42, Code = "XING", Description = "CROSSING" },
        new StreetSuffixCode() { Id = 43, Code = "XRD", Description = "CROSSROAD" },
        new StreetSuffixCode() { Id = 44, Code = "XRDS", Description = "CROSSROADS" },
        new StreetSuffixCode() { Id = 45, Code = "CURV", Description = "CURVE" },
        new StreetSuffixCode() { Id = 46, Code = "DL", Description = "DALE" },
        new StreetSuffixCode() { Id = 47, Code = "DM", Description = "DAM" },
        new StreetSuffixCode() { Id = 48, Code = "DV", Description = "DIVIDE" },
        new StreetSuffixCode() { Id = 49, Code = "DR", Description = "DRIVE" },
        new StreetSuffixCode() { Id = 50, Code = "DRS", Description = "DRIVES" },
        new StreetSuffixCode() { Id = 51, Code = "EST", Description = "ESTATE" },
        new StreetSuffixCode() { Id = 52, Code = "ESTS", Description = "ESTATES" },
        new StreetSuffixCode() { Id = 53, Code = "EXPY", Description = "EXPRESSWAY" },
        new StreetSuffixCode() { Id = 54, Code = "EXT", Description = "EXTENSION" },
        new StreetSuffixCode() { Id = 55, Code = "EXTS", Description = "EXTENSIONS" },
        new StreetSuffixCode() { Id = 56, Code = "FALL", Description = "FALL" },
        new StreetSuffixCode() { Id = 57, Code = "FLS", Description = "FALLS" },
        new StreetSuffixCode() { Id = 58, Code = "FRY", Description = "FERRY" },
        new StreetSuffixCode() { Id = 59, Code = "FLD", Description = "FIELD" },
        new StreetSuffixCode() { Id = 60, Code = "FLDS", Description = "FIELDS" },
        new StreetSuffixCode() { Id = 61, Code = "FLT", Description = "FLAT" },
        new StreetSuffixCode() { Id = 62, Code = "FLTS", Description = "FLATS" },
        new StreetSuffixCode() { Id = 63, Code = "FRD", Description = "FORD" },
        new StreetSuffixCode() { Id = 64, Code = "FRDS", Description = "FORDS" },
        new StreetSuffixCode() { Id = 65, Code = "FRST", Description = "FOREST" },
        new StreetSuffixCode() { Id = 66, Code = "FRG", Description = "FORGE" },
        new StreetSuffixCode() { Id = 67, Code = "FRGS", Description = "FORGES" },
        new StreetSuffixCode() { Id = 68, Code = "FRK", Description = "FORK" },
        new StreetSuffixCode() { Id = 69, Code = "FRKS", Description = "FORKS" },
        new StreetSuffixCode() { Id = 70, Code = "FT", Description = "FORT" },
        new StreetSuffixCode() { Id = 71, Code = "FWY", Description = "FREEWAY" },
        new StreetSuffixCode() { Id = 72, Code = "GDN", Description = "GARDEN" },
        new StreetSuffixCode() { Id = 73, Code = "GDNS", Description = "GARDENS" },
        new StreetSuffixCode() { Id = 74, Code = "GTWY", Description = "GATEWAY" },
        new StreetSuffixCode() { Id = 75, Code = "GLN", Description = "GLEN" },
        new StreetSuffixCode() { Id = 76, Code = "GLNS", Description = "GLENS" },
        new StreetSuffixCode() { Id = 77, Code = "GRN", Description = "GREEN" },
        new StreetSuffixCode() { Id = 78, Code = "GRNS", Description = "GREENS" },
        new StreetSuffixCode() { Id = 79, Code = "GRV", Description = "GROVE" },
        new StreetSuffixCode() { Id = 80, Code = "GRVS", Description = "GROVES" },
        new StreetSuffixCode() { Id = 81, Code = "HBR", Description = "HARBOR" },
        new StreetSuffixCode() { Id = 82, Code = "HBRS", Description = "HARBORS" },
        new StreetSuffixCode() { Id = 83, Code = "HVN", Description = "HAVEN" },
        new StreetSuffixCode() { Id = 84, Code = "HTS", Description = "HEIGHTS" },
        new StreetSuffixCode() { Id = 85, Code = "HWY", Description = "HIGHWAY" },
        new StreetSuffixCode() { Id = 86, Code = "HL", Description = "HILL" },
        new StreetSuffixCode() { Id = 87, Code = "HLS", Description = "HILLS" },
        new StreetSuffixCode() { Id = 88, Code = "HOLW", Description = "HOLLOW" },
        new StreetSuffixCode() { Id = 89, Code = "INLT", Description = "INLET" },
        new StreetSuffixCode() { Id = 90, Code = "IS", Description = "ISLAND" },
        new StreetSuffixCode() { Id = 91, Code = "ISS", Description = "ISLANDS" },
        new StreetSuffixCode() { Id = 92, Code = "ISLE", Description = "ISLE" },
        new StreetSuffixCode() { Id = 93, Code = "JCT", Description = "JUNCTION" },
        new StreetSuffixCode() { Id = 94, Code = "JCTS", Description = "JUNCTIONS" },
        new StreetSuffixCode() { Id = 95, Code = "KY", Description = "KEY" },
        new StreetSuffixCode() { Id = 96, Code = "KYS", Description = "KEYS" },
        new StreetSuffixCode() { Id = 97, Code = "KNL", Description = "KNOLL" },
        new StreetSuffixCode() { Id = 98, Code = "KNLS", Description = "KNOLLS" },
        new StreetSuffixCode() { Id = 99, Code = "LK", Description = "LAKE" },
        new StreetSuffixCode() { Id = 100, Code = "LKS", Description = "LAKES" },
        new StreetSuffixCode() { Id = 101, Code = "LNDG", Description = "LANDING" },
        new StreetSuffixCode() { Id = 102, Code = "LN", Description = "LANE" },
        new StreetSuffixCode() { Id = 103, Code = "LGT", Description = "LIGHT" },
        new StreetSuffixCode() { Id = 104, Code = "LGTS", Description = "LIGHTS" },
        new StreetSuffixCode() { Id = 105, Code = "LF", Description = "LOAF" },
        new StreetSuffixCode() { Id = 106, Code = "LCK", Description = "LOCK" },
        new StreetSuffixCode() { Id = 107, Code = "LCKS", Description = "LOCKS" },
        new StreetSuffixCode() { Id = 108, Code = "LDG", Description = "LODGE" },
        new StreetSuffixCode() { Id = 109, Code = "LOOP", Description = "LOOP" },
        new StreetSuffixCode() { Id = 110, Code = "MALL", Description = "MALL" },
        new StreetSuffixCode() { Id = 111, Code = "MNR", Description = "MANOR" },
        new StreetSuffixCode() { Id = 112, Code = "MNRS", Description = "MANORS" },
        new StreetSuffixCode() { Id = 113, Code = "MDW", Description = "MEADOW" },
        new StreetSuffixCode() { Id = 114, Code = "MDWS", Description = "MEADOWS" },
        new StreetSuffixCode() { Id = 115, Code = "MEWS", Description = "MEWS" },
        new StreetSuffixCode() { Id = 116, Code = "ML", Description = "MILL" },
        new StreetSuffixCode() { Id = 117, Code = "MLS", Description = "MILLS" },
        new StreetSuffixCode() { Id = 118, Code = "MSN", Description = "MISSION" },
        new StreetSuffixCode() { Id = 119, Code = "MTWY", Description = "MOTORWAY" },
        new StreetSuffixCode() { Id = 120, Code = "MT", Description = "MOUNT" },
        new StreetSuffixCode() { Id = 121, Code = "MTN", Description = "MOUNTAIN" },
        new StreetSuffixCode() { Id = 122, Code = "MTNS", Description = "MOUNTAINS" },
        new StreetSuffixCode() { Id = 123, Code = "NCK", Description = "NECK" },
        new StreetSuffixCode() { Id = 124, Code = "ORCH", Description = "ORCHARD" },
        new StreetSuffixCode() { Id = 125, Code = "OVAL", Description = "OVL" },
        new StreetSuffixCode() { Id = 126, Code = "OPAS", Description = "OVERPASS" },
        new StreetSuffixCode() { Id = 127, Code = "PARK", Description = "PARK" },
        new StreetSuffixCode() { Id = 128, Code = "PKWY", Description = "PARKWAY" },
        new StreetSuffixCode() { Id = 129, Code = "PKWY", Description = "PARKWAYS" },
        new StreetSuffixCode() { Id = 130, Code = "PASS", Description = "PASS" },
        new StreetSuffixCode() { Id = 131, Code = "PSGE", Description = "PASSAGE" },
        new StreetSuffixCode() { Id = 132, Code = "PATH", Description = "PATH" },
        new StreetSuffixCode() { Id = 133, Code = "PIKE", Description = "PIKE" },
        new StreetSuffixCode() { Id = 134, Code = "PNE", Description = "PINE" },
        new StreetSuffixCode() { Id = 135, Code = "PL", Description = "PLACE" },
        new StreetSuffixCode() { Id = 136, Code = "PLN", Description = "PLAIN" },
        new StreetSuffixCode() { Id = 137, Code = "PLNS", Description = "PLAINS" },
        new StreetSuffixCode() { Id = 138, Code = "PLZ", Description = "PLAZA" },
        new StreetSuffixCode() { Id = 139, Code = "PT", Description = "POINT" },
        new StreetSuffixCode() { Id = 140, Code = "PTS", Description = "POINTS" },
        new StreetSuffixCode() { Id = 141, Code = "PRT", Description = "PORT" },
        new StreetSuffixCode() { Id = 142, Code = "PRTS", Description = "PORTS" },
        new StreetSuffixCode() { Id = 143, Code = "PR", Description = "PRAIRIE" },
        new StreetSuffixCode() { Id = 144, Code = "RADL", Description = "RADIAL" },
        new StreetSuffixCode() { Id = 145, Code = "RAMP", Description = "RAMP" },
        new StreetSuffixCode() { Id = 146, Code = "RNCH", Description = "RANCH" },
        new StreetSuffixCode() { Id = 147, Code = "RPD", Description = "RAPID" },
        new StreetSuffixCode() { Id = 148, Code = "RPDS", Description = "RAPIDS" },
        new StreetSuffixCode() { Id = 149, Code = "RST", Description = "REST" },
        new StreetSuffixCode() { Id = 150, Code = "RDG", Description = "RIDGE" },
        new StreetSuffixCode() { Id = 151, Code = "RDGS", Description = "RIDGES" },
        new StreetSuffixCode() { Id = 152, Code = "RIV", Description = "RIVER" },
        new StreetSuffixCode() { Id = 153, Code = "RD", Description = "ROAD" },
        new StreetSuffixCode() { Id = 154, Code = "RDS", Description = "ROADS" },
        new StreetSuffixCode() { Id = 155, Code = "RTE", Description = "ROUTE" },
        new StreetSuffixCode() { Id = 156, Code = "ROW", Description = "ROW" },
        new StreetSuffixCode() { Id = 157, Code = "RUE", Description = "RUE" },
        new StreetSuffixCode() { Id = 158, Code = "RUN", Description = "RUN" },
        new StreetSuffixCode() { Id = 159, Code = "SHL", Description = "SHOAL" },
        new StreetSuffixCode() { Id = 160, Code = "SHLS", Description = "SHOALS" },
        new StreetSuffixCode() { Id = 161, Code = "SHR", Description = "SHORE" },
        new StreetSuffixCode() { Id = 162, Code = "SHRS", Description = "SHORES" },
        new StreetSuffixCode() { Id = 163, Code = "SKWY", Description = "SKYWAY" },
        new StreetSuffixCode() { Id = 164, Code = "SPG", Description = "SPRING" },
        new StreetSuffixCode() { Id = 165, Code = "SPGS", Description = "SPRINGS" },
        new StreetSuffixCode() { Id = 166, Code = "SPUR", Description = "SPURS" },
        new StreetSuffixCode() { Id = 167, Code = "SQ", Description = "SQUARE" },
        new StreetSuffixCode() { Id = 168, Code = "SQS", Description = "SQUARES" },
        new StreetSuffixCode() { Id = 169, Code = "STA", Description = "STATION" },
        new StreetSuffixCode() { Id = 170, Code = "STRA", Description = "STRAVENUE" },
        new StreetSuffixCode() { Id = 171, Code = "STRM", Description = "STREAM" },
        new StreetSuffixCode() { Id = 172, Code = "ST", Description = "STREET" },
        new StreetSuffixCode() { Id = 173, Code = "STS", Description = "STREETS" },
        new StreetSuffixCode() { Id = 174, Code = "SMT", Description = "SUMMIT" },
        new StreetSuffixCode() { Id = 175, Code = "TER", Description = "TERRACE" },
        new StreetSuffixCode() { Id = 176, Code = "TRWY", Description = "THROUGHWAY" },
        new StreetSuffixCode() { Id = 177, Code = "TRCE", Description = "TRACE" },
        new StreetSuffixCode() { Id = 178, Code = "TRAK", Description = "TRACK" },
        new StreetSuffixCode() { Id = 179, Code = "TRFY", Description = "TRAFFICWAY" },
        new StreetSuffixCode() { Id = 180, Code = "TRL", Description = "TRAIL" },
        new StreetSuffixCode() { Id = 181, Code = "TRLR", Description = "TRAILER" },
        new StreetSuffixCode() { Id = 182, Code = "TUNL", Description = "TUNNEL" },
        new StreetSuffixCode() { Id = 183, Code = "TPKE", Description = "TURNPIKE" },
        new StreetSuffixCode() { Id = 184, Code = "UPAS", Description = "UNDERPASS" },
        new StreetSuffixCode() { Id = 185, Code = "UN", Description = "UNION" },
        new StreetSuffixCode() { Id = 186, Code = "UNS", Description = "UNIONS" },
        new StreetSuffixCode() { Id = 187, Code = "VLY", Description = "VALLEY" },
        new StreetSuffixCode() { Id = 188, Code = "VLYS", Description = "VALLEYS" },
        new StreetSuffixCode() { Id = 189, Code = "VIA", Description = "VIADUCT" },
        new StreetSuffixCode() { Id = 190, Code = "VW", Description = "VIEW" },
        new StreetSuffixCode() { Id = 191, Code = "VWS", Description = "VIEWS" },
        new StreetSuffixCode() { Id = 192, Code = "VLG", Description = "VILLAGE" },
        new StreetSuffixCode() { Id = 193, Code = "VLGS", Description = "VILLAGES" },
        new StreetSuffixCode() { Id = 194, Code = "VL", Description = "VILLE" },
        new StreetSuffixCode() { Id = 195, Code = "VIS", Description = "VISTA" },
        new StreetSuffixCode() { Id = 196, Code = "WALK", Description = "WALK" },
        new StreetSuffixCode() { Id = 197, Code = "WALL", Description = "WALL" },
        new StreetSuffixCode() { Id = 198, Code = "WAY", Description = "WY" },
        new StreetSuffixCode() { Id = 199, Code = "WAYS", Description = "WYS" },
        new StreetSuffixCode() { Id = 200, Code = "WL", Description = "WELL" },
        new StreetSuffixCode() { Id = 201, Code = "WLS", Description = "WELLS" }
    });

      private readonly List<StreetSuffixAlias> StreetSuffixAliasTable = new List<StreetSuffixAlias>(new StreetSuffixAlias[] {
        new StreetSuffixAlias() { Id = 1, ForeignId = 1, AliasName = "ALLEE" },
        new StreetSuffixAlias() { Id = 2, ForeignId = 1, AliasName = "ALLY" },
        new StreetSuffixAlias() { Id = 3, ForeignId = 2, AliasName = "ANNEX" },
        new StreetSuffixAlias() { Id = 4, ForeignId = 2, AliasName = "ANNX" },
        new StreetSuffixAlias() { Id = 5, ForeignId = 4, AliasName = "AV" },
        new StreetSuffixAlias() { Id = 6, ForeignId = 4, AliasName = "AVEN" },
        new StreetSuffixAlias() { Id = 7, ForeignId = 4, AliasName = "AVENU" },
        new StreetSuffixAlias() { Id = 8, ForeignId = 4, AliasName = "AVN" },
        new StreetSuffixAlias() { Id = 9, ForeignId = 4, AliasName = "AVNUE" },
        new StreetSuffixAlias() { Id = 10, ForeignId = 5, AliasName = "BAYOO" },
        new StreetSuffixAlias() { Id = 11, ForeignId = 8, AliasName = "BLUF" },
        new StreetSuffixAlias() { Id = 12, ForeignId = 10, AliasName = "BOT" },
        new StreetSuffixAlias() { Id = 13, ForeignId = 10, AliasName = "BOTTM" },
        new StreetSuffixAlias() { Id = 14, ForeignId = 11, AliasName = "BOUL" },
        new StreetSuffixAlias() { Id = 15, ForeignId = 11, AliasName = "BOULV" },
        new StreetSuffixAlias() { Id = 16, ForeignId = 12, AliasName = "BRNCH" },
        new StreetSuffixAlias() { Id = 17, ForeignId = 13, AliasName = "BRDGE" },
        new StreetSuffixAlias() { Id = 18, ForeignId = 18, AliasName = "BYPA" },
        new StreetSuffixAlias() { Id = 19, ForeignId = 18, AliasName = "BYPAS" },
        new StreetSuffixAlias() { Id = 20, ForeignId = 18, AliasName = "BYPS" },
        new StreetSuffixAlias() { Id = 21, ForeignId = 19, AliasName = "CMP" },
        new StreetSuffixAlias() { Id = 22, ForeignId = 20, AliasName = "CANYN" },
        new StreetSuffixAlias() { Id = 23, ForeignId = 20, AliasName = "CNYN" },
        new StreetSuffixAlias() { Id = 24, ForeignId = 22, AliasName = "CAUSWAY" },
        new StreetSuffixAlias() { Id = 25, ForeignId = 23, AliasName = "CEN" },
        new StreetSuffixAlias() { Id = 26, ForeignId = 23, AliasName = "CENT" },
        new StreetSuffixAlias() { Id = 27, ForeignId = 23, AliasName = "CENTR" },
        new StreetSuffixAlias() { Id = 28, ForeignId = 23, AliasName = "CENTRE" },
        new StreetSuffixAlias() { Id = 29, ForeignId = 23, AliasName = "CNTER" },
        new StreetSuffixAlias() { Id = 30, ForeignId = 23, AliasName = "CNTR" },
        new StreetSuffixAlias() { Id = 31, ForeignId = 25, AliasName = "CIRC" },
        new StreetSuffixAlias() { Id = 32, ForeignId = 25, AliasName = "CIRCL" },
        new StreetSuffixAlias() { Id = 33, ForeignId = 25, AliasName = "CRCL" },
        new StreetSuffixAlias() { Id = 34, ForeignId = 25, AliasName = "CRCLE" },
        new StreetSuffixAlias() { Id = 35, ForeignId = 35, AliasName = "CRT" },
        new StreetSuffixAlias() { Id = 36, ForeignId = 39, AliasName = "CR" },
        new StreetSuffixAlias() { Id = 37, ForeignId = 39, AliasName = "CK" },
        new StreetSuffixAlias() { Id = 38, ForeignId = 40, AliasName = "CRECENT" },
        new StreetSuffixAlias() { Id = 39, ForeignId = 40, AliasName = "CRESENT" },
        new StreetSuffixAlias() { Id = 40, ForeignId = 40, AliasName = "CRSNT" },
        new StreetSuffixAlias() { Id = 41, ForeignId = 40, AliasName = "CRSCNT" },
        new StreetSuffixAlias() { Id = 42, ForeignId = 40, AliasName = "CRSENT" },
        new StreetSuffixAlias() { Id = 43, ForeignId = 42, AliasName = "CRSSING" },
        new StreetSuffixAlias() { Id = 44, ForeignId = 42, AliasName = "CRSSNG" },
        new StreetSuffixAlias() { Id = 45, ForeignId = 48, AliasName = "DIV" },
        new StreetSuffixAlias() { Id = 46, ForeignId = 48, AliasName = "DVD" },
        new StreetSuffixAlias() { Id = 47, ForeignId = 49, AliasName = "DRV" },
        new StreetSuffixAlias() { Id = 48, ForeignId = 49, AliasName = "DRIV" },
        new StreetSuffixAlias() { Id = 49, ForeignId = 53, AliasName = "EXP" },
        new StreetSuffixAlias() { Id = 50, ForeignId = 53, AliasName = "EXPR" },
        new StreetSuffixAlias() { Id = 51, ForeignId = 53, AliasName = "EXPRESS" },
        new StreetSuffixAlias() { Id = 52, ForeignId = 53, AliasName = "EXPW" },
        new StreetSuffixAlias() { Id = 53, ForeignId = 54, AliasName = "EXTN" },
        new StreetSuffixAlias() { Id = 54, ForeignId = 54, AliasName = "EXTNSN" },
        new StreetSuffixAlias() { Id = 55, ForeignId = 55, AliasName = "EXTENSIONS" },
        new StreetSuffixAlias() { Id = 56, ForeignId = 58, AliasName = "FRRY" },
        new StreetSuffixAlias() { Id = 57, ForeignId = 65, AliasName = "FORESTS" },
        new StreetSuffixAlias() { Id = 58, ForeignId = 66, AliasName = "FORG" },
        new StreetSuffixAlias() { Id = 59, ForeignId = 67, AliasName = "FORGES" },
        new StreetSuffixAlias() { Id = 60, ForeignId = 70, AliasName = "FRT" },
        new StreetSuffixAlias() { Id = 61, ForeignId = 71, AliasName = "FREEWY" },
        new StreetSuffixAlias() { Id = 62, ForeignId = 71, AliasName = "FRWAY" },
        new StreetSuffixAlias() { Id = 63, ForeignId = 71, AliasName = "FRWY" },
        new StreetSuffixAlias() { Id = 64, ForeignId = 72, AliasName = "GRDEN" },
        new StreetSuffixAlias() { Id = 65, ForeignId = 72, AliasName = "GRDN" },
        new StreetSuffixAlias() { Id = 66, ForeignId = 72, AliasName = "GARDN" },
        new StreetSuffixAlias() { Id = 67, ForeignId = 73, AliasName = "GRDNS" },
        new StreetSuffixAlias() { Id = 68, ForeignId = 74, AliasName = "GATEWY" },
        new StreetSuffixAlias() { Id = 69, ForeignId = 74, AliasName = "GATWAY" },
        new StreetSuffixAlias() { Id = 70, ForeignId = 74, AliasName = "GTWAY" },
        new StreetSuffixAlias() { Id = 71, ForeignId = 79, AliasName = "GROV" },
        new StreetSuffixAlias() { Id = 72, ForeignId = 81, AliasName = "HRBOR" },
        new StreetSuffixAlias() { Id = 73, ForeignId = 81, AliasName = "HARBR" },
        new StreetSuffixAlias() { Id = 74, ForeignId = 81, AliasName = "HARB" },
        new StreetSuffixAlias() { Id = 75, ForeignId = 83, AliasName = "HAVN" },
        new StreetSuffixAlias() { Id = 76, ForeignId = 84, AliasName = "HT" },
        new StreetSuffixAlias() { Id = 77, ForeignId = 84, AliasName = "HEIGHT" },
        new StreetSuffixAlias() { Id = 78, ForeignId = 84, AliasName = "HGTS" },
        new StreetSuffixAlias() { Id = 79, ForeignId = 85, AliasName = "HWAY" },
        new StreetSuffixAlias() { Id = 80, ForeignId = 85, AliasName = "HIWAY" },
        new StreetSuffixAlias() { Id = 81, ForeignId = 85, AliasName = "HIWY" },
        new StreetSuffixAlias() { Id = 82, ForeignId = 85, AliasName = "HIGHWY" },
        new StreetSuffixAlias() { Id = 83, ForeignId = 88, AliasName = "HLLW" },
        new StreetSuffixAlias() { Id = 84, ForeignId = 88, AliasName = "HOLLOWS" },
        new StreetSuffixAlias() { Id = 85, ForeignId = 88, AliasName = "HOLWS" },
        new StreetSuffixAlias() { Id = 86, ForeignId = 90, AliasName = "ISLND" },
        new StreetSuffixAlias() { Id = 87, ForeignId = 91, AliasName = "ISLNDS" },
        new StreetSuffixAlias() { Id = 88, ForeignId = 92, AliasName = "ISLES" },
        new StreetSuffixAlias() { Id = 89, ForeignId = 93, AliasName = "JUNCTN" },
        new StreetSuffixAlias() { Id = 90, ForeignId = 93, AliasName = "JUNCTON" },
        new StreetSuffixAlias() { Id = 91, ForeignId = 93, AliasName = "JCTION" },
        new StreetSuffixAlias() { Id = 92, ForeignId = 93, AliasName = "JCTN" },
        new StreetSuffixAlias() { Id = 93, ForeignId = 94, AliasName = "JCTNS" },
        new StreetSuffixAlias() { Id = 94, ForeignId = 97, AliasName = "KNOL" },
        new StreetSuffixAlias() { Id = 95, ForeignId = 98, AliasName = "KNOLLS" },
        new StreetSuffixAlias() { Id = 96, ForeignId = 101, AliasName = "LNDNG" },
        new StreetSuffixAlias() { Id = 97, ForeignId = 102, AliasName = "LA" },
        new StreetSuffixAlias() { Id = 98, ForeignId = 102, AliasName = "LANES" },
        new StreetSuffixAlias() { Id = 99, ForeignId = 108, AliasName = "LDGE" },
        new StreetSuffixAlias() { Id = 100, ForeignId = 108, AliasName = "LODG" },
        new StreetSuffixAlias() { Id = 101, ForeignId = 109, AliasName = "LOOPS" },
        new StreetSuffixAlias() { Id = 102, ForeignId = 114, AliasName = "MEDOWS" },
        new StreetSuffixAlias() { Id = 103, ForeignId = 118, AliasName = "MISSN" },
        new StreetSuffixAlias() { Id = 104, ForeignId = 118, AliasName = "MSSN" },
        new StreetSuffixAlias() { Id = 105, ForeignId = 120, AliasName = "MNT" },
        new StreetSuffixAlias() { Id = 106, ForeignId = 121, AliasName = "MNTAIN" },
        new StreetSuffixAlias() { Id = 107, ForeignId = 121, AliasName = "MNTN" },
        new StreetSuffixAlias() { Id = 108, ForeignId = 121, AliasName = "MOUNTIN" },
        new StreetSuffixAlias() { Id = 109, ForeignId = 121, AliasName = "MTIN" },
        new StreetSuffixAlias() { Id = 110, ForeignId = 122, AliasName = "MNTNS" },
        new StreetSuffixAlias() { Id = 111, ForeignId = 124, AliasName = "ORCHRD" },
        new StreetSuffixAlias() { Id = 112, ForeignId = 127, AliasName = "PK" },
        new StreetSuffixAlias() { Id = 113, ForeignId = 127, AliasName = "PRK" },
        new StreetSuffixAlias() { Id = 114, ForeignId = 128, AliasName = "PARKWY" },
        new StreetSuffixAlias() { Id = 115, ForeignId = 128, AliasName = "PKWAY" },
        new StreetSuffixAlias() { Id = 116, ForeignId = 128, AliasName = "PKWYS" },
        new StreetSuffixAlias() { Id = 117, ForeignId = 128, AliasName = "PKY" },
        new StreetSuffixAlias() { Id = 118, ForeignId = 132, AliasName = "PATHS" },
        new StreetSuffixAlias() { Id = 119, ForeignId = 133, AliasName = "PIKES" },
        new StreetSuffixAlias() { Id = 120, ForeignId = 137, AliasName = "PLAINES" },
        new StreetSuffixAlias() { Id = 121, ForeignId = 138, AliasName = "PLZA" },
        new StreetSuffixAlias() { Id = 122, ForeignId = 143, AliasName = "PRARIE" },
        new StreetSuffixAlias() { Id = 123, ForeignId = 143, AliasName = "PRR" },
        new StreetSuffixAlias() { Id = 124, ForeignId = 144, AliasName = "RAD" },
        new StreetSuffixAlias() { Id = 125, ForeignId = 144, AliasName = "RADIEL" },
        new StreetSuffixAlias() { Id = 126, ForeignId = 146, AliasName = "RANCHES" },
        new StreetSuffixAlias() { Id = 127, ForeignId = 146, AliasName = "RNCHS" },
        new StreetSuffixAlias() { Id = 128, ForeignId = 150, AliasName = "RDGE" },
        new StreetSuffixAlias() { Id = 129, ForeignId = 152, AliasName = "RIVR" },
        new StreetSuffixAlias() { Id = 130, ForeignId = 152, AliasName = "RVR" },
        new StreetSuffixAlias() { Id = 131, ForeignId = 161, AliasName = "SHOAR" },
        new StreetSuffixAlias() { Id = 132, ForeignId = 162, AliasName = "SHOARS" },
        new StreetSuffixAlias() { Id = 133, ForeignId = 164, AliasName = "SPNG" },
        new StreetSuffixAlias() { Id = 134, ForeignId = 164, AliasName = "SPRNG" },
        new StreetSuffixAlias() { Id = 135, ForeignId = 165, AliasName = "SPRNGS" },
        new StreetSuffixAlias() { Id = 136, ForeignId = 165, AliasName = "SPNGS" },
        new StreetSuffixAlias() { Id = 137, ForeignId = 166, AliasName = "SPURS" },
        new StreetSuffixAlias() { Id = 138, ForeignId = 167, AliasName = "SQR" },
        new StreetSuffixAlias() { Id = 139, ForeignId = 167, AliasName = "SQRE" },
        new StreetSuffixAlias() { Id = 140, ForeignId = 167, AliasName = "SQU" },
        new StreetSuffixAlias() { Id = 141, ForeignId = 168, AliasName = "SQRS" },
        new StreetSuffixAlias() { Id = 142, ForeignId = 169, AliasName = "STATN" },
        new StreetSuffixAlias() { Id = 143, ForeignId = 169, AliasName = "STN" },
        new StreetSuffixAlias() { Id = 144, ForeignId = 170, AliasName = "STRAV" },
        new StreetSuffixAlias() { Id = 145, ForeignId = 170, AliasName = "STRAVE" },
        new StreetSuffixAlias() { Id = 146, ForeignId = 170, AliasName = "STRAVEN" },
        new StreetSuffixAlias() { Id = 147, ForeignId = 170, AliasName = "STRAVN" },
        new StreetSuffixAlias() { Id = 148, ForeignId = 170, AliasName = "STRVN" },
        new StreetSuffixAlias() { Id = 149, ForeignId = 170, AliasName = "STRVNUE" },
        new StreetSuffixAlias() { Id = 150, ForeignId = 171, AliasName = "STREME" },
        new StreetSuffixAlias() { Id = 151, ForeignId = 172, AliasName = "STRT" },
        new StreetSuffixAlias() { Id = 152, ForeignId = 172, AliasName = "STR" },
        new StreetSuffixAlias() { Id = 153, ForeignId = 174, AliasName = "SUMIT" },
        new StreetSuffixAlias() { Id = 154, ForeignId = 174, AliasName = "SUMITT" },
        new StreetSuffixAlias() { Id = 155, ForeignId = 175, AliasName = "TERR" },
        new StreetSuffixAlias() { Id = 156, ForeignId = 177, AliasName = "TRACES" },
        new StreetSuffixAlias() { Id = 157, ForeignId = 178, AliasName = "TRACKS" },
        new StreetSuffixAlias() { Id = 158, ForeignId = 178, AliasName = "TRK" },
        new StreetSuffixAlias() { Id = 159, ForeignId = 178, AliasName = "TRKS" },
        new StreetSuffixAlias() { Id = 160, ForeignId = 180, AliasName = "TRAILS" },
        new StreetSuffixAlias() { Id = 161, ForeignId = 180, AliasName = "TRLS" },
        new StreetSuffixAlias() { Id = 162, ForeignId = 180, AliasName = "TR" },
        new StreetSuffixAlias() { Id = 164, ForeignId = 181, AliasName = "TRLRS" },
        new StreetSuffixAlias() { Id = 165, ForeignId = 182, AliasName = "TUNEL" },
        new StreetSuffixAlias() { Id = 166, ForeignId = 182, AliasName = "TUNLS" },
        new StreetSuffixAlias() { Id = 167, ForeignId = 182, AliasName = "TUNNELS" },
        new StreetSuffixAlias() { Id = 168, ForeignId = 182, AliasName = "TUNNL" },
        new StreetSuffixAlias() { Id = 169, ForeignId = 183, AliasName = "TPK" },
        new StreetSuffixAlias() { Id = 170, ForeignId = 183, AliasName = "TRNPK" },
        new StreetSuffixAlias() { Id = 171, ForeignId = 183, AliasName = "TRPK" },
        new StreetSuffixAlias() { Id = 172, ForeignId = 183, AliasName = "TURNPK" },
        new StreetSuffixAlias() { Id = 173, ForeignId = 187, AliasName = "VALLY" },
        new StreetSuffixAlias() { Id = 174, ForeignId = 189, AliasName = "VDCT" },
        new StreetSuffixAlias() { Id = 175, ForeignId = 189, AliasName = "VIADCT" },
        new StreetSuffixAlias() { Id = 176, ForeignId = 192, AliasName = "VILL" },
        new StreetSuffixAlias() { Id = 177, ForeignId = 192, AliasName = "VILLAG" },
        new StreetSuffixAlias() { Id = 178, ForeignId = 192, AliasName = "VILLG" },
        new StreetSuffixAlias() { Id = 179, ForeignId = 192, AliasName = "VILLIAGE" },
        new StreetSuffixAlias() { Id = 180, ForeignId = 195, AliasName = "VIST" },
        new StreetSuffixAlias() { Id = 181, ForeignId = 187, AliasName = "VLLY" },
        new StreetSuffixAlias() { Id = 182, ForeignId = 195, AliasName = "VST" },
        new StreetSuffixAlias() { Id = 183, ForeignId = 195, AliasName = "VSTA" }
    });

      private readonly List<StreetSecondaryUnitAlias> StreetSecondaryUnitAliasTable = new List<StreetSecondaryUnitAlias>(new StreetSecondaryUnitAlias[] {
        new StreetSecondaryUnitAlias() { Id = 1, AliasName = "APPARTMENT", ForeignId = 2 }
    });

      private readonly List<StreetSecondaryUnitCode> StreetSecondaryUnitTable = new List<StreetSecondaryUnitCode>(new StreetSecondaryUnitCode[] {
        new StreetSecondaryUnitCode() { Id = 1, Description = "SUITE", Code = "STE", RequiresRange = true },
        new StreetSecondaryUnitCode() { Id = 2, Description = "APARTMENT", Code = "APT", RequiresRange = true },
        new StreetSecondaryUnitCode() { Id = 3, Description = "DEPARTMENT", Code = "DEPT", RequiresRange = true },
        new StreetSecondaryUnitCode() { Id = 4, Description = "ROOM", Code = "RM", RequiresRange = true },
        new StreetSecondaryUnitCode() { Id = 5, Description = "FLOOR", Code = "FL", RequiresRange = true },
        new StreetSecondaryUnitCode() { Id = 6, Description = "UNIT", Code = "UNIT", RequiresRange = true },
        new StreetSecondaryUnitCode() { Id = 7, Description = "BUILDING", Code = "BLDG", RequiresRange = true },
        new StreetSecondaryUnitCode() { Id = 8, Description = "HANGAR", Code = "HNGR", RequiresRange = true },
        new StreetSecondaryUnitCode() { Id = 9, Description = "KEY", Code = "KEY", RequiresRange = true },
        new StreetSecondaryUnitCode() { Id = 10, Description = "LOT", Code = "LOT", RequiresRange = true },
        new StreetSecondaryUnitCode() { Id = 11, Description = "PIER", Code = "PIER", RequiresRange = true },
        new StreetSecondaryUnitCode() { Id = 12, Description = "SLIP", Code = "SLIP", RequiresRange = true },
        new StreetSecondaryUnitCode() { Id = 13, Description = "SPACE", Code = "SPACE", RequiresRange = true },
        new StreetSecondaryUnitCode() { Id = 14, Description = "STOP", Code = "STOP", RequiresRange = true },
        new StreetSecondaryUnitCode() { Id = 15, Description = "TRAILER", Code = "TRLR", RequiresRange = true },
        new StreetSecondaryUnitCode() { Id = 16, Description = "BOX", Code = "BOX", RequiresRange = true },
        new StreetSecondaryUnitCode() { Id = 17, Description = "BASEMENT", Code = "BSMT", RequiresRange = false },
        new StreetSecondaryUnitCode() { Id = 18, Description = "FRONT", Code = "FRNT", RequiresRange = false },
        new StreetSecondaryUnitCode() { Id = 19, Description = "LOBBY", Code = "LBBY", RequiresRange = false },
        new StreetSecondaryUnitCode() { Id = 20, Description = "LOWER", Code = "LOWR", RequiresRange = false },
        new StreetSecondaryUnitCode() { Id = 21, Description = "OFFICE", Code = "OFC", RequiresRange = false },
        new StreetSecondaryUnitCode() { Id = 22, Description = "PENTHOUSE", Code = "PH", RequiresRange = false },
        new StreetSecondaryUnitCode() { Id = 23, Description = "REAR", Code = "REAR", RequiresRange = false },
        new StreetSecondaryUnitCode() { Id = 24, Description = "SIDE", Code = "SIDE", RequiresRange = false },
        new StreetSecondaryUnitCode() { Id = 25, Description = "UPPER", Code = "UPPR", RequiresRange = false }
    });

      private readonly List<StateCode> StateTable = new List<StateCode>(new StateCode[] {
        new StateCode() { Id = 2, Code = "AB", CountryCodeId = 37, Description = "ALBERTA" },
        new StateCode() { Id = 3, Code = "BC", CountryCodeId = 37, Description = "BRITISH COLUMBIA" },
        new StateCode() { Id = 4, Code = "MB", CountryCodeId = 37, Description = "MANITOBA" },
        new StateCode() { Id = 5, Code = "NB", CountryCodeId = 37, Description = "NEW BRUNSWICK" },
        new StateCode() { Id = 6, Code = "NL", CountryCodeId = 37, Description = "NEWFOUNDLAND AND LABRADOR" },
        new StateCode() { Id = 7, Code = "NS", CountryCodeId = 37, Description = "NOVA SCOTIA" },
        new StateCode() { Id = 8, Code = "NT", CountryCodeId = 37, Description = "NORTHWEST TERRITORIES" },
        new StateCode() { Id = 9, Code = "NU", CountryCodeId = 37, Description = "NUNAVUT TERRITORY" },
        new StateCode() { Id = 10, Code = "ON", CountryCodeId = 37, Description = "ONTARIO" },
        new StateCode() { Id = 11, Code = "PE", CountryCodeId = 37, Description = "PRINCE EDWARD ISLAND" },
        new StateCode() { Id = 12, Code = "QC", CountryCodeId = 37, Description = "QUEBEC" },
        new StateCode() { Id = 13, Code = "SK", CountryCodeId = 37, Description = "SASKATCHEWAN" },
        new StateCode() { Id = 14, Code = "YT", CountryCodeId = 37, Description = "YUKON" },
        new StateCode() { Id = 15, Code = "AK", CountryCodeId = 226, Description = "ALASKA" },
        new StateCode() { Id = 16, Code = "AL", CountryCodeId = 226, Description = "ALABAMA" },
        new StateCode() { Id = 17, Code = "AR", CountryCodeId = 226, Description = "ARKANSAS" },
        new StateCode() { Id = 18, Code = "AZ", CountryCodeId = 226, Description = "ARIZONA" },
        new StateCode() { Id = 19, Code = "CA", CountryCodeId = 226, Description = "CALIFORNIA" },
        new StateCode() { Id = 20, Code = "CO", CountryCodeId = 226, Description = "COLORADO" },
        new StateCode() { Id = 21, Code = "CT", CountryCodeId = 226, Description = "CONNECTICUT" },
        new StateCode() { Id = 22, Code = "DC", CountryCodeId = 226, Description = "DISTRICT OF COLUMBIA" },
        new StateCode() { Id = 23, Code = "DE", CountryCodeId = 226, Description = "DELAWARE" },
        new StateCode() { Id = 24, Code = "FL", CountryCodeId = 226, Description = "FLORIDA" },
        new StateCode() { Id = 25, Code = "GA", CountryCodeId = 226, Description = "GEORGIA" },
        new StateCode() { Id = 26, Code = "HI", CountryCodeId = 226, Description = "HAWAII" },
        new StateCode() { Id = 27, Code = "IA", CountryCodeId = 226, Description = "IOWA" },
        new StateCode() { Id = 28, Code = "ID", CountryCodeId = 226, Description = "IDAHO" },
        new StateCode() { Id = 29, Code = "IL", CountryCodeId = 226, Description = "ILLINOIS" },
        new StateCode() { Id = 30, Code = "IN", CountryCodeId = 226, Description = "INDIANA" },
        new StateCode() { Id = 31, Code = "KS", CountryCodeId = 226, Description = "KANSAS" },
        new StateCode() { Id = 32, Code = "KY", CountryCodeId = 226, Description = "KENTUCKY" },
        new StateCode() { Id = 33, Code = "LA", CountryCodeId = 226, Description = "LOUISIANA" },
        new StateCode() { Id = 34, Code = "MA", CountryCodeId = 226, Description = "MASSACHUSETTS" },
        new StateCode() { Id = 35, Code = "MD", CountryCodeId = 226, Description = "MARYLAND" },
        new StateCode() { Id = 36, Code = "ME", CountryCodeId = 226, Description = "MAINE" },
        new StateCode() { Id = 37, Code = "MI", CountryCodeId = 226, Description = "MICHIGAN" },
        new StateCode() { Id = 38, Code = "MN", CountryCodeId = 226, Description = "MINNESOTA" },
        new StateCode() { Id = 39, Code = "MO", CountryCodeId = 226, Description = "MISSOURI" },
        new StateCode() { Id = 40, Code = "MS", CountryCodeId = 226, Description = "MISSISSIPPI" },
        new StateCode() { Id = 41, Code = "MT", CountryCodeId = 226, Description = "MONTANA" },
        new StateCode() { Id = 42, Code = "NE", CountryCodeId = 226, Description = "NEBRASKA" },
        new StateCode() { Id = 43, Code = "NC", CountryCodeId = 226, Description = "NORTH CAROLINA" },
        new StateCode() { Id = 44, Code = "ND", CountryCodeId = 226, Description = "NORTH DAKOTA" },
        new StateCode() { Id = 45, Code = "NH", CountryCodeId = 226, Description = "NEW HAMPSHIRE" },
        new StateCode() { Id = 46, Code = "NJ", CountryCodeId = 226, Description = "NEW JERSEY" },
        new StateCode() { Id = 47, Code = "NM", CountryCodeId = 226, Description = "NEW MEXICO" },
        new StateCode() { Id = 48, Code = "NV", CountryCodeId = 226, Description = "NEVADA" },
        new StateCode() { Id = 49, Code = "NY", CountryCodeId = 226, Description = "NEW YORK" },
        new StateCode() { Id = 50, Code = "OH", CountryCodeId = 226, Description = "OHIO" },
        new StateCode() { Id = 51, Code = "OK", CountryCodeId = 226, Description = "OKLAHOMA" },
        new StateCode() { Id = 52, Code = "OR", CountryCodeId = 226, Description = "OREGON" },
        new StateCode() { Id = 53, Code = "PA", CountryCodeId = 226, Description = "PENNSYLVANIA" },
        new StateCode() { Id = 54, Code = "RI", CountryCodeId = 226, Description = "RHODE ISLAND" },
        new StateCode() { Id = 55, Code = "SC", CountryCodeId = 226, Description = "SOUTH CAROLINA" },
        new StateCode() { Id = 56, Code = "SD", CountryCodeId = 226, Description = "SOUTH DAKOTA" },
        new StateCode() { Id = 57, Code = "TN", CountryCodeId = 226, Description = "TENNESSEE" },
        new StateCode() { Id = 58, Code = "TX", CountryCodeId = 226, Description = "TEXAS" },
        new StateCode() { Id = 59, Code = "UT", CountryCodeId = 226, Description = "UTAH" },
        new StateCode() { Id = 60, Code = "VA", CountryCodeId = 226, Description = "VIRGINIA" },
        new StateCode() { Id = 61, Code = "VT", CountryCodeId = 226, Description = "VERMONT" },
        new StateCode() { Id = 62, Code = "WA", CountryCodeId = 226, Description = "WASHINGTON" },
        new StateCode() { Id = 63, Code = "WI", CountryCodeId = 226, Description = "WISCONSIN" },
        new StateCode() { Id = 64, Code = "WV", CountryCodeId = 226, Description = "WEST VIRGINIA" },
        new StateCode() { Id = 65, Code = "WY", CountryCodeId = 226, Description = "WYOMING" },
        new StateCode() { Id = 66, Code = "AS", CountryCodeId = 226, Description = "AMERICAN SAMOA" },
        new StateCode() { Id = 68, Code = "FM", CountryCodeId = 226, Description = "FEDERATED STATES OF MICRONESIA" },
        new StateCode() { Id = 69, Code = "GU", CountryCodeId = 226, Description = "GUAM" },
        new StateCode() { Id = 70, Code = "MH", CountryCodeId = 226, Description = "MARSHALL ISLANDS" },
        new StateCode() { Id = 71, Code = "MP", CountryCodeId = 226, Description = "NORTHERN MARIANA ISLANDS" },
        new StateCode() { Id = 72, Code = "PW", CountryCodeId = 226, Description = "PALAU" },
        new StateCode() { Id = 73, Code = "PR", CountryCodeId = 226, Description = "PUERTO RICO" },
        new StateCode() { Id = 74, Code = "VI", CountryCodeId = 226, Description = "VIRGIN ISLANDS" }
    });

      private readonly List<StateAlias> StateAbrvLegacyTable = new List<StateAlias>(new StateAlias[] {
        new StateAlias() { Id = 1,  ForeignId = 15, AliasName = "ARIZ" },
        new StateAlias() { Id = 2,  ForeignId = 17, AliasName = "ARK" },
        new StateAlias() { Id = 3,  ForeignId = 19, AliasName = "CAL" },
        new StateAlias() { Id = 4,  ForeignId = 19, AliasName = "CALIF" },
        new StateAlias() { Id = 5,  ForeignId = 20, AliasName = "COL" },
        new StateAlias() { Id = 6,  ForeignId = 20, AliasName = "COLO" },
        new StateAlias() { Id = 7,  ForeignId = 21, AliasName = "CONN" },
        new StateAlias() { Id = 8,  ForeignId = 23, AliasName = "DEL" },
        new StateAlias() { Id = 9,  ForeignId = 24, AliasName = "FLA" },
        new StateAlias() { Id = 10,  ForeignId = 25, AliasName = "GEO" },
        new StateAlias() { Id = 11,  ForeignId = 29, AliasName = "ILL" },
        new StateAlias() { Id = 12,  ForeignId = 30, AliasName = "IND" },
        new StateAlias() { Id = 13,  ForeignId = 31, AliasName = "KAN" },
        new StateAlias() { Id = 14,  ForeignId = 31, AliasName = "KANS" },
        new StateAlias() { Id = 15,  ForeignId = 34, AliasName = "MASS" },
        new StateAlias() { Id = 16,  ForeignId = 37, AliasName = "MICH" },
        new StateAlias() { Id = 17,  ForeignId = 40, AliasName = "MISS" },
        new StateAlias() { Id = 18,  ForeignId = 41, AliasName = "MONT" },
        new StateAlias() { Id = 19,  ForeignId = 42, AliasName = "NEB" },
        new StateAlias() { Id = 20,  ForeignId = 42, AliasName = "NEBR" },
        new StateAlias() { Id = 20,  ForeignId = 42, AliasName = "NB" },
        new StateAlias() { Id = 21,  ForeignId = 48, AliasName = "NEV" },
        new StateAlias() { Id = 22,  ForeignId = 51, AliasName = "OKLA" },
        new StateAlias() { Id = 23,  ForeignId = 52, AliasName = "ORE" },
        new StateAlias() { Id = 24,  ForeignId = 53, AliasName = "PENN" },
        new StateAlias() { Id = 25,  ForeignId = 53, AliasName = "PENNA" },
        new StateAlias() { Id = 26,  ForeignId = 57, AliasName = "TENN" },
        new StateAlias() { Id = 27,  ForeignId = 58, AliasName = "TEX" },
        new StateAlias() { Id = 28,  ForeignId = 62, AliasName = "WASH" },
        new StateAlias() { Id = 29,  ForeignId = 63, AliasName = "WIS" },
        new StateAlias() { Id = 30,  ForeignId = 63, AliasName = "WISC" },
        new StateAlias() { Id = 31,  ForeignId = 65, AliasName = "WYO" }
    });

      private readonly List<CountryAlias> CountryAliasTable = new List<CountryAlias>(new CountryAlias[] {
        new CountryAlias() { Id = 1, AliasName = "A.D.", ForeignId = 1 },
        new CountryAlias() { Id = 2, AliasName = "A.E.", ForeignId = 2 },
        new CountryAlias() { Id = 3, AliasName = "A.F.", ForeignId = 3 },
        new CountryAlias() { Id = 4, AliasName = "A.G.", ForeignId = 4 },
        new CountryAlias() { Id = 5, AliasName = "A.I.", ForeignId = 5 },
        new CountryAlias() { Id = 6, AliasName = "A.L.", ForeignId = 6 },
        new CountryAlias() { Id = 7, AliasName = "A.M.", ForeignId = 7 },
        new CountryAlias() { Id = 8, AliasName = "A.N.", ForeignId = 8 },
        new CountryAlias() { Id = 9, AliasName = "A.O.", ForeignId = 9 },
        new CountryAlias() { Id = 10, AliasName = "A.Q.", ForeignId = 10 },
        new CountryAlias() { Id = 11, AliasName = "A.R.", ForeignId = 11 },
        new CountryAlias() { Id = 12, AliasName = "A.S.", ForeignId = 12 },
        new CountryAlias() { Id = 13, AliasName = "A.T.", ForeignId = 13 },
        new CountryAlias() { Id = 14, AliasName = "A.U.", ForeignId = 14 },
        new CountryAlias() { Id = 15, AliasName = "A.W.", ForeignId = 15 },
        new CountryAlias() { Id = 16, AliasName = "A.X.", ForeignId = 16 },
        new CountryAlias() { Id = 17, AliasName = "A.Z.", ForeignId = 17 },
        new CountryAlias() { Id = 18, AliasName = "B.A.", ForeignId = 18 },
        new CountryAlias() { Id = 19, AliasName = "B.B.", ForeignId = 19 },
        new CountryAlias() { Id = 20, AliasName = "B.D.", ForeignId = 20 },
        new CountryAlias() { Id = 21, AliasName = "B.E.", ForeignId = 21 },
        new CountryAlias() { Id = 22, AliasName = "B.F.", ForeignId = 22 },
        new CountryAlias() { Id = 23, AliasName = "B.G.", ForeignId = 23 },
        new CountryAlias() { Id = 24, AliasName = "B.H.", ForeignId = 24 },
        new CountryAlias() { Id = 25, AliasName = "B.I.", ForeignId = 25 },
        new CountryAlias() { Id = 26, AliasName = "B.J.", ForeignId = 26 },
        new CountryAlias() { Id = 27, AliasName = "B.M.", ForeignId = 27 },
        new CountryAlias() { Id = 28, AliasName = "B.N.", ForeignId = 28 },
        new CountryAlias() { Id = 29, AliasName = "B.O.", ForeignId = 29 },
        new CountryAlias() { Id = 30, AliasName = "B.R.", ForeignId = 30 },
        new CountryAlias() { Id = 31, AliasName = "B.S.", ForeignId = 31 },
        new CountryAlias() { Id = 32, AliasName = "B.T.", ForeignId = 32 },
        new CountryAlias() { Id = 33, AliasName = "B.V.", ForeignId = 33 },
        new CountryAlias() { Id = 35, AliasName = "B.W.", ForeignId = 35 },
        new CountryAlias() { Id = 36, AliasName = "B.Z.", ForeignId = 36 },
        new CountryAlias() { Id = 37, AliasName = "C.A.", ForeignId = 37 },
        new CountryAlias() { Id = 38, AliasName = "C.C.", ForeignId = 38 },
        new CountryAlias() { Id = 39, AliasName = "C.D.", ForeignId = 39 },
        new CountryAlias() { Id = 40, AliasName = "C.F.", ForeignId = 40 },
        new CountryAlias() { Id = 41, AliasName = "C.G.", ForeignId = 41 },
        new CountryAlias() { Id = 42, AliasName = "C.H.", ForeignId = 42 },
        new CountryAlias() { Id = 43, AliasName = "C.I.", ForeignId = 43 },
        new CountryAlias() { Id = 44, AliasName = "C.K.", ForeignId = 44 },
        new CountryAlias() { Id = 45, AliasName = "C.L.", ForeignId = 45 },
        new CountryAlias() { Id = 46, AliasName = "C.M.", ForeignId = 46 },
        new CountryAlias() { Id = 47, AliasName = "C.N.", ForeignId = 47 },
        new CountryAlias() { Id = 48, AliasName = "C.O.", ForeignId = 48 },
        new CountryAlias() { Id = 49, AliasName = "C.R.", ForeignId = 49 },
        new CountryAlias() { Id = 50, AliasName = "C.S.", ForeignId = 50 },
        new CountryAlias() { Id = 51, AliasName = "C.U.", ForeignId = 51 },
        new CountryAlias() { Id = 52, AliasName = "C.V.", ForeignId = 52 },
        new CountryAlias() { Id = 53, AliasName = "C.X.", ForeignId = 53 },
        new CountryAlias() { Id = 54, AliasName = "C.Y.", ForeignId = 54 },
        new CountryAlias() { Id = 55, AliasName = "C.Z.", ForeignId = 55 },
        new CountryAlias() { Id = 56, AliasName = "D.E.", ForeignId = 56 },
        new CountryAlias() { Id = 57, AliasName = "D.J.", ForeignId = 57 },
        new CountryAlias() { Id = 58, AliasName = "D.K.", ForeignId = 58 },
        new CountryAlias() { Id = 59, AliasName = "D.M.", ForeignId = 59 },
        new CountryAlias() { Id = 60, AliasName = "D.O.", ForeignId = 60 },
        new CountryAlias() { Id = 61, AliasName = "D.Z.", ForeignId = 61 },
        new CountryAlias() { Id = 62, AliasName = "E.C.", ForeignId = 62 },
        new CountryAlias() { Id = 63, AliasName = "E.E.", ForeignId = 63 },
        new CountryAlias() { Id = 64, AliasName = "E.G.", ForeignId = 64 },
        new CountryAlias() { Id = 65, AliasName = "E.H.", ForeignId = 65 },
        new CountryAlias() { Id = 66, AliasName = "E.R.", ForeignId = 66 },
        new CountryAlias() { Id = 67, AliasName = "E.S.", ForeignId = 67 },
        new CountryAlias() { Id = 68, AliasName = "E.T.", ForeignId = 68 },
        new CountryAlias() { Id = 69, AliasName = "F.I.", ForeignId = 69 },
        new CountryAlias() { Id = 70, AliasName = "F.J.", ForeignId = 70 },
        new CountryAlias() { Id = 71, AliasName = "F.K.", ForeignId = 71 },
        new CountryAlias() { Id = 72, AliasName = "F.M.", ForeignId = 72 },
        new CountryAlias() { Id = 73, AliasName = "F.O.", ForeignId = 73 },
        new CountryAlias() { Id = 74, AliasName = "F.R.", ForeignId = 74 },
        new CountryAlias() { Id = 75, AliasName = "F.X.", ForeignId = 75 },
        new CountryAlias() { Id = 76, AliasName = "G.A.", ForeignId = 76 },
        new CountryAlias() { Id = 77, AliasName = "G.B.", ForeignId = 77 },
        new CountryAlias() { Id = 78, AliasName = "G.D.", ForeignId = 78 },
        new CountryAlias() { Id = 79, AliasName = "G.E.", ForeignId = 79 },
        new CountryAlias() { Id = 80, AliasName = "G.F.", ForeignId = 80 },
        new CountryAlias() { Id = 81, AliasName = "G.H.", ForeignId = 81 },
        new CountryAlias() { Id = 82, AliasName = "G.I.", ForeignId = 82 },
        new CountryAlias() { Id = 83, AliasName = "G.L.", ForeignId = 83 },
        new CountryAlias() { Id = 84, AliasName = "G.M.", ForeignId = 84 },
        new CountryAlias() { Id = 85, AliasName = "G.N.", ForeignId = 85 },
        new CountryAlias() { Id = 86, AliasName = "G.P.", ForeignId = 86 },
        new CountryAlias() { Id = 87, AliasName = "G.Q.", ForeignId = 87 },
        new CountryAlias() { Id = 88, AliasName = "G.R.", ForeignId = 88 },
        new CountryAlias() { Id = 89, AliasName = "G.S.", ForeignId = 89 },
        new CountryAlias() { Id = 90, AliasName = "G.T.", ForeignId = 90 },
        new CountryAlias() { Id = 91, AliasName = "G.U.", ForeignId = 91 },
        new CountryAlias() { Id = 92, AliasName = "G.W.", ForeignId = 92 },
        new CountryAlias() { Id = 93, AliasName = "G.Y.", ForeignId = 93 },
        new CountryAlias() { Id = 94, AliasName = "H.K.", ForeignId = 94 },
        new CountryAlias() { Id = 95, AliasName = "H.M.", ForeignId = 95 },
        new CountryAlias() { Id = 96, AliasName = "H.N.", ForeignId = 96 },
        new CountryAlias() { Id = 97, AliasName = "H.R.", ForeignId = 97 },
        new CountryAlias() { Id = 98, AliasName = "H.T.", ForeignId = 98 },
        new CountryAlias() { Id = 99, AliasName = "H.U.", ForeignId = 99 },
        new CountryAlias() { Id = 100, AliasName = "I.D.", ForeignId = 100 },
        new CountryAlias() { Id = 101, AliasName = "I.E.", ForeignId = 101 },
        new CountryAlias() { Id = 102, AliasName = "I.L.", ForeignId = 102 },
        new CountryAlias() { Id = 103, AliasName = "I.N.", ForeignId = 103 },
        new CountryAlias() { Id = 104, AliasName = "I.O.", ForeignId = 104 },
        new CountryAlias() { Id = 105, AliasName = "I.Q.", ForeignId = 105 },
        new CountryAlias() { Id = 106, AliasName = "I.R.", ForeignId = 106 },
        new CountryAlias() { Id = 107, AliasName = "I.T.", ForeignId = 107 },
        new CountryAlias() { Id = 108, AliasName = "J.M.", ForeignId = 108 },
        new CountryAlias() { Id = 109, AliasName = "J.O.", ForeignId = 109 },
        new CountryAlias() { Id = 110, AliasName = "J.P.", ForeignId = 110 },
        new CountryAlias() { Id = 111, AliasName = "K.E.", ForeignId = 111 },
        new CountryAlias() { Id = 112, AliasName = "K.G.", ForeignId = 112 },
        new CountryAlias() { Id = 113, AliasName = "K.H.", ForeignId = 113 },
        new CountryAlias() { Id = 114, AliasName = "K.I.", ForeignId = 114 },
        new CountryAlias() { Id = 115, AliasName = "K.M.", ForeignId = 115 },
        new CountryAlias() { Id = 116, AliasName = "K.N.", ForeignId = 116 },
        new CountryAlias() { Id = 117, AliasName = "K.P.", ForeignId = 117 },
        new CountryAlias() { Id = 118, AliasName = "K.R.", ForeignId = 118 },
        new CountryAlias() { Id = 119, AliasName = "K.W.", ForeignId = 119 },
        new CountryAlias() { Id = 120, AliasName = "K.Y.", ForeignId = 120 },
        new CountryAlias() { Id = 121, AliasName = "K.Z.", ForeignId = 121 },
        new CountryAlias() { Id = 122, AliasName = "L.A.", ForeignId = 122 },
        new CountryAlias() { Id = 123, AliasName = "L.B.", ForeignId = 123 },
        new CountryAlias() { Id = 124, AliasName = "L.C.", ForeignId = 124 },
        new CountryAlias() { Id = 125, AliasName = "L.I.", ForeignId = 125 },
        new CountryAlias() { Id = 126, AliasName = "L.K.", ForeignId = 126 },
        new CountryAlias() { Id = 127, AliasName = "L.R.", ForeignId = 127 },
        new CountryAlias() { Id = 128, AliasName = "L.S.", ForeignId = 128 },
        new CountryAlias() { Id = 129, AliasName = "L.T.", ForeignId = 129 },
        new CountryAlias() { Id = 130, AliasName = "L.U.", ForeignId = 130 },
        new CountryAlias() { Id = 131, AliasName = "L.V.", ForeignId = 131 },
        new CountryAlias() { Id = 132, AliasName = "L.Y.", ForeignId = 132 },
        new CountryAlias() { Id = 133, AliasName = "M.A.", ForeignId = 133 },
        new CountryAlias() { Id = 134, AliasName = "M.C.", ForeignId = 134 },
        new CountryAlias() { Id = 135, AliasName = "M.D.", ForeignId = 135 },
        new CountryAlias() { Id = 136, AliasName = "M.G.", ForeignId = 136 },
        new CountryAlias() { Id = 137, AliasName = "M.H.", ForeignId = 137 },
        new CountryAlias() { Id = 138, AliasName = "M.K.", ForeignId = 138 },
        new CountryAlias() { Id = 139, AliasName = "M.L.", ForeignId = 139 },
        new CountryAlias() { Id = 140, AliasName = "M.M.", ForeignId = 140 },
        new CountryAlias() { Id = 141, AliasName = "M.N.", ForeignId = 141 },
        new CountryAlias() { Id = 142, AliasName = "M.O.", ForeignId = 142 },
        new CountryAlias() { Id = 143, AliasName = "M.P.", ForeignId = 143 },
        new CountryAlias() { Id = 144, AliasName = "M.Q.", ForeignId = 144 },
        new CountryAlias() { Id = 145, AliasName = "M.R.", ForeignId = 145 },
        new CountryAlias() { Id = 146, AliasName = "M.S.", ForeignId = 146 },
        new CountryAlias() { Id = 147, AliasName = "M.T.", ForeignId = 147 },
        new CountryAlias() { Id = 148, AliasName = "M.U.", ForeignId = 148 },
        new CountryAlias() { Id = 149, AliasName = "M.V.", ForeignId = 149 },
        new CountryAlias() { Id = 150, AliasName = "M.W.", ForeignId = 150 },
        new CountryAlias() { Id = 151, AliasName = "M.X.", ForeignId = 151 },
        new CountryAlias() { Id = 152, AliasName = "M.Y.", ForeignId = 152 },
        new CountryAlias() { Id = 153, AliasName = "M.Z.", ForeignId = 153 },
        new CountryAlias() { Id = 154, AliasName = "N.A.", ForeignId = 154 },
        new CountryAlias() { Id = 155, AliasName = "N.C.", ForeignId = 155 },
        new CountryAlias() { Id = 156, AliasName = "N.E.", ForeignId = 156 },
        new CountryAlias() { Id = 157, AliasName = "N.F.", ForeignId = 157 },
        new CountryAlias() { Id = 158, AliasName = "N.G.", ForeignId = 158 },
        new CountryAlias() { Id = 159, AliasName = "N.I.", ForeignId = 159 },
        new CountryAlias() { Id = 160, AliasName = "N.L.", ForeignId = 160 },
        new CountryAlias() { Id = 161, AliasName = "N.O.", ForeignId = 161 },
        new CountryAlias() { Id = 162, AliasName = "N.P.", ForeignId = 162 },
        new CountryAlias() { Id = 163, AliasName = "N.R.", ForeignId = 163 },
        new CountryAlias() { Id = 164, AliasName = "N.U.", ForeignId = 164 },
        new CountryAlias() { Id = 165, AliasName = "N.Z.", ForeignId = 165 },
        new CountryAlias() { Id = 166, AliasName = "O.M.", ForeignId = 166 },
        new CountryAlias() { Id = 167, AliasName = "P.A.", ForeignId = 167 },
        new CountryAlias() { Id = 168, AliasName = "P.E.", ForeignId = 168 },
        new CountryAlias() { Id = 169, AliasName = "P.F.", ForeignId = 169 },
        new CountryAlias() { Id = 170, AliasName = "P.G.", ForeignId = 170 },
        new CountryAlias() { Id = 171, AliasName = "P.H.", ForeignId = 171 },
        new CountryAlias() { Id = 172, AliasName = "P.K.", ForeignId = 172 },
        new CountryAlias() { Id = 173, AliasName = "P.L.", ForeignId = 173 },
        new CountryAlias() { Id = 174, AliasName = "P.M.", ForeignId = 174 },
        new CountryAlias() { Id = 175, AliasName = "P.N.", ForeignId = 175 },
        new CountryAlias() { Id = 176, AliasName = "P.R.", ForeignId = 176 },
        new CountryAlias() { Id = 177, AliasName = "P.S.", ForeignId = 177 },
        new CountryAlias() { Id = 178, AliasName = "P.T.", ForeignId = 178 },
        new CountryAlias() { Id = 179, AliasName = "P.W.", ForeignId = 179 },
        new CountryAlias() { Id = 180, AliasName = "P.Y.", ForeignId = 180 },
        new CountryAlias() { Id = 181, AliasName = "Q.A.", ForeignId = 181 },
        new CountryAlias() { Id = 182, AliasName = "R.E.", ForeignId = 182 },
        new CountryAlias() { Id = 183, AliasName = "R.O.", ForeignId = 183 },
        new CountryAlias() { Id = 184, AliasName = "R.U.", ForeignId = 184 },
        new CountryAlias() { Id = 185, AliasName = "R.W.", ForeignId = 185 },
        new CountryAlias() { Id = 186, AliasName = "S.A.", ForeignId = 186 },
        new CountryAlias() { Id = 187, AliasName = "S.B.", ForeignId = 187 },
        new CountryAlias() { Id = 188, AliasName = "S.C.", ForeignId = 188 },
        new CountryAlias() { Id = 189, AliasName = "S.D.", ForeignId = 189 },
        new CountryAlias() { Id = 190, AliasName = "S.E.", ForeignId = 190 },
        new CountryAlias() { Id = 191, AliasName = "S.G.", ForeignId = 191 },
        new CountryAlias() { Id = 192, AliasName = "S.H.", ForeignId = 192 },
        new CountryAlias() { Id = 193, AliasName = "S.I.", ForeignId = 193 },
        new CountryAlias() { Id = 194, AliasName = "S.J.", ForeignId = 194 },
        new CountryAlias() { Id = 195, AliasName = "S.K.", ForeignId = 195 },
        new CountryAlias() { Id = 196, AliasName = "S.L.", ForeignId = 196 },
        new CountryAlias() { Id = 197, AliasName = "S.M.", ForeignId = 197 },
        new CountryAlias() { Id = 198, AliasName = "S.N.", ForeignId = 198 },
        new CountryAlias() { Id = 199, AliasName = "S.O.", ForeignId = 199 },
        new CountryAlias() { Id = 200, AliasName = "S.R.", ForeignId = 200 },
        new CountryAlias() { Id = 201, AliasName = "S.T.", ForeignId = 201 },
        new CountryAlias() { Id = 202, AliasName = "S.U.", ForeignId = 202 },
        new CountryAlias() { Id = 203, AliasName = "S.V.", ForeignId = 203 },
        new CountryAlias() { Id = 204, AliasName = "S.Y.", ForeignId = 204 },
        new CountryAlias() { Id = 205, AliasName = "S.Z.", ForeignId = 205 },
        new CountryAlias() { Id = 206, AliasName = "T.C.", ForeignId = 206 },
        new CountryAlias() { Id = 207, AliasName = "T.D.", ForeignId = 207 },
        new CountryAlias() { Id = 208, AliasName = "T.G.", ForeignId = 208 },
        new CountryAlias() { Id = 209, AliasName = "T.H.", ForeignId = 209 },
        new CountryAlias() { Id = 210, AliasName = "T.J.", ForeignId = 210 },
        new CountryAlias() { Id = 211, AliasName = "T.K.", ForeignId = 211 },
        new CountryAlias() { Id = 212, AliasName = "T.L.", ForeignId = 212 },
        new CountryAlias() { Id = 213, AliasName = "T.M.", ForeignId = 213 },
        new CountryAlias() { Id = 214, AliasName = "T.N.", ForeignId = 214 },
        new CountryAlias() { Id = 215, AliasName = "T.O.", ForeignId = 215 },
        new CountryAlias() { Id = 216, AliasName = "T.P.", ForeignId = 216 },
        new CountryAlias() { Id = 217, AliasName = "T.R.", ForeignId = 217 },
        new CountryAlias() { Id = 218, AliasName = "T.T.", ForeignId = 218 },
        new CountryAlias() { Id = 219, AliasName = "T.V.", ForeignId = 219 },
        new CountryAlias() { Id = 220, AliasName = "T.W.", ForeignId = 220 },
        new CountryAlias() { Id = 221, AliasName = "T.Z.", ForeignId = 221 },
        new CountryAlias() { Id = 222, AliasName = "U.A.", ForeignId = 222 },
        new CountryAlias() { Id = 223, AliasName = "U.G.", ForeignId = 223 },
        new CountryAlias() { Id = 224, AliasName = "U.K.", ForeignId = 224 },
        new CountryAlias() { Id = 225, AliasName = "U.M.", ForeignId = 225 },
        new CountryAlias() { Id = 226, AliasName = "U.S.", ForeignId = 226 },
        new CountryAlias() { Id = 227, AliasName = "U.Y.", ForeignId = 227 },
        new CountryAlias() { Id = 228, AliasName = "U.Z.", ForeignId = 228 },
        new CountryAlias() { Id = 229, AliasName = "V.A.", ForeignId = 229 },
        new CountryAlias() { Id = 230, AliasName = "V.C.", ForeignId = 230 },
        new CountryAlias() { Id = 231, AliasName = "V.E.", ForeignId = 231 },
        new CountryAlias() { Id = 232, AliasName = "V.G.", ForeignId = 232 },
        new CountryAlias() { Id = 233, AliasName = "V.I.", ForeignId = 233 },
        new CountryAlias() { Id = 234, AliasName = "V.N.", ForeignId = 234 },
        new CountryAlias() { Id = 235, AliasName = "V.U.", ForeignId = 235 },
        new CountryAlias() { Id = 236, AliasName = "W.F.", ForeignId = 236 },
        new CountryAlias() { Id = 237, AliasName = "W.S.", ForeignId = 237 },
        new CountryAlias() { Id = 238, AliasName = "Y.E.", ForeignId = 238 },
        new CountryAlias() { Id = 239, AliasName = "Y.T.", ForeignId = 239 },
        new CountryAlias() { Id = 240, AliasName = "Y.U.", ForeignId = 240 },
        new CountryAlias() { Id = 241, AliasName = "Z.A.", ForeignId = 241 },
        new CountryAlias() { Id = 242, AliasName = "Z.M.", ForeignId = 242 },
        new CountryAlias() { Id = 243, AliasName = "Z.R.", ForeignId = 243 },
        new CountryAlias() { Id = 244, AliasName = "Z.W.", ForeignId = 244 },
        new CountryAlias() { Id = 245, AliasName = "USA", ForeignId = 226 },
        new CountryAlias() { Id = 246, AliasName = "U.S.A.", ForeignId = 226 },
        new CountryAlias() { Id = 247, AliasName = "ENGLAND", ForeignId = 224 },
        new CountryAlias() { Id = 248, AliasName = "GB", ForeignId = 224 },
        new CountryAlias() { Id = 249, AliasName = "G.B.", ForeignId = 224 },
        new CountryAlias() { Id = 250, AliasName = "RUSSIA", ForeignId = 202 },
        new CountryAlias() { Id = 251, AliasName = "U.S.S.R.", ForeignId = 202 },
        new CountryAlias() { Id = 252, AliasName = "USSR", ForeignId = 202 }
    });

      private readonly List<CountryCode> CountryTable = new List<CountryCode>(new CountryCode[] {
        new CountryCode() { Id = 1, Code = "AD", Description = "Andorra" },
        new CountryCode() { Id = 2, Code = "AE", Description = "United Arab Emirates" },
        new CountryCode() { Id = 3, Code = "AF", Description = "Afghanistan" },
        new CountryCode() { Id = 4, Code = "AG", Description = "Antigua and Barbuda" },
        new CountryCode() { Id = 5, Code = "AI", Description = "Anguilla" },
        new CountryCode() { Id = 6, Code = "AL", Description = "Albania" },
        new CountryCode() { Id = 7, Code = "AM", Description = "Armenia" },
        new CountryCode() { Id = 8, Code = "AN", Description = "Antilles - Netherlands" },
        new CountryCode() { Id = 9, Code = "AO", Description = "Angola" },
        new CountryCode() { Id = 10, Code = "AQ", Description = "Antarctica" },
        new CountryCode() { Id = 11, Code = "AR", Description = "Argentina" },
        new CountryCode() { Id = 12, Code = "AS", Description = "American Samoa" },
        new CountryCode() { Id = 13, Code = "AT", Description = "Austria" },
        new CountryCode() { Id = 14, Code = "AU", Description = "Australia" },
        new CountryCode() { Id = 15, Code = "AW", Description = "Aruba" },
        new CountryCode() { Id = 16, Code = "AX", Description = "Aland Islands" },
        new CountryCode() { Id = 17, Code = "AZ", Description = "Azerbaijan" },
        new CountryCode() { Id = 18, Code = "BA", Description = "Bosnia and Herzegovina" },
        new CountryCode() { Id = 19, Code = "BB", Description = "Barbados" },
        new CountryCode() { Id = 20, Code = "BD", Description = "Bangladesh" },
        new CountryCode() { Id = 21, Code = "BE", Description = "Belgium" },
        new CountryCode() { Id = 22, Code = "BF", Description = "Burkina Faso" },
        new CountryCode() { Id = 23, Code = "BG", Description = "Bulgaria" },
        new CountryCode() { Id = 24, Code = "BH", Description = "Bahrain" },
        new CountryCode() { Id = 25, Code = "BI", Description = "Burundi" },
        new CountryCode() { Id = 26, Code = "BJ", Description = "Benin" },
        new CountryCode() { Id = 27, Code = "BM", Description = "Bermuda" },
        new CountryCode() { Id = 28, Code = "BN", Description = "Brunei Darussalam" },
        new CountryCode() { Id = 29, Code = "BO", Description = "Bolivia" },
        new CountryCode() { Id = 30, Code = "BR", Description = "Brazil" },
        new CountryCode() { Id = 31, Code = "BS", Description = "Bahamas" },
        new CountryCode() { Id = 32, Code = "BT", Description = "Bhutan" },
        new CountryCode() { Id = 33, Code = "BV", Description = "Bouvet Island" },
        new CountryCode() { Id = 35, Code = "BW", Description = "Botswana" },
        new CountryCode() { Id = 36, Code = "BZ", Description = "Belize" },
        new CountryCode() { Id = 37, Code = "CA", Description = "Canada" },
        new CountryCode() { Id = 38, Code = "CC", Description = "Cocos (Keeling) Islands" },
        new CountryCode() { Id = 39, Code = "CD", Description = "Democratic Republic of the Congo" },
        new CountryCode() { Id = 40, Code = "CF", Description = "Central African Republic" },
        new CountryCode() { Id = 41, Code = "CG", Description = "Congo" },
        new CountryCode() { Id = 42, Code = "CH", Description = "Switzerland" },
        new CountryCode() { Id = 43, Code = "CI", Description = "Cote D'Ivoire (Ivory Coast)" },
        new CountryCode() { Id = 44, Code = "CK", Description = "Cook Islands" },
        new CountryCode() { Id = 45, Code = "CL", Description = "Chile" },
        new CountryCode() { Id = 46, Code = "CM", Description = "Cameroon" },
        new CountryCode() { Id = 47, Code = "CN", Description = "China" },
        new CountryCode() { Id = 48, Code = "CO", Description = "Colombia" },
        new CountryCode() { Id = 49, Code = "CR", Description = "Costa Rica" },
        new CountryCode() { Id = 50, Code = "CS", Description = "Serbia and Montenegro" },
        new CountryCode() { Id = 51, Code = "CU", Description = "Cuba" },
        new CountryCode() { Id = 52, Code = "CV", Description = "Cape Verde" },
        new CountryCode() { Id = 53, Code = "CX", Description = "Christmas Island" },
        new CountryCode() { Id = 54, Code = "CY", Description = "Cyprus" },
        new CountryCode() { Id = 55, Code = "CZ", Description = "Czech Republic" },
        new CountryCode() { Id = 56, Code = "DE", Description = "Germany" },
        new CountryCode() { Id = 57, Code = "DJ", Description = "Djibouti" },
        new CountryCode() { Id = 58, Code = "DK", Description = "Denmark" },
        new CountryCode() { Id = 59, Code = "DM", Description = "Dominica" },
        new CountryCode() { Id = 60, Code = "DO", Description = "Dominican Republic" },
        new CountryCode() { Id = 61, Code = "DZ", Description = "Algeria" },
        new CountryCode() { Id = 62, Code = "EC", Description = "Ecuador" },
        new CountryCode() { Id = 63, Code = "EE", Description = "Estonia" },
        new CountryCode() { Id = 64, Code = "EG", Description = "Egypt" },
        new CountryCode() { Id = 65, Code = "EH", Description = "Western Sahara" },
        new CountryCode() { Id = 66, Code = "ER", Description = "Eritrea" },
        new CountryCode() { Id = 67, Code = "ES", Description = "Spain" },
        new CountryCode() { Id = 68, Code = "ET", Description = "Ethiopia" },
        new CountryCode() { Id = 69, Code = "FI", Description = "Finland" },
        new CountryCode() { Id = 70, Code = "FJ", Description = "Fiji" },
        new CountryCode() { Id = 71, Code = "FK", Description = "Falkland Islands (Malvinas)" },
        new CountryCode() { Id = 72, Code = "FM", Description = "Federated States of Micronesia" },
        new CountryCode() { Id = 73, Code = "FO", Description = "Faroe Islands" },
        new CountryCode() { Id = 74, Code = "FR", Description = "France" },
        new CountryCode() { Id = 75, Code = "FX", Description = "France, Metropolitan" },
        new CountryCode() { Id = 76, Code = "GA", Description = "Gabon" },
        new CountryCode() { Id = 77, Code = "GB", Description = "Great Britain (UK)" },
        new CountryCode() { Id = 78, Code = "GD", Description = "Grenada" },
        new CountryCode() { Id = 79, Code = "GE", Description = "Georgia" },
        new CountryCode() { Id = 80, Code = "GF", Description = "French Guiana" },
        new CountryCode() { Id = 81, Code = "GH", Description = "Ghana" },
        new CountryCode() { Id = 82, Code = "GI", Description = "Gibraltar" },
        new CountryCode() { Id = 83, Code = "GL", Description = "Greenland" },
        new CountryCode() { Id = 84, Code = "GM", Description = "Gambia" },
        new CountryCode() { Id = 85, Code = "GN", Description = "Guinea" },
        new CountryCode() { Id = 86, Code = "GP", Description = "Guadeloupe" },
        new CountryCode() { Id = 87, Code = "GQ", Description = "Equatorial Guinea" },
        new CountryCode() { Id = 88, Code = "GR", Description = "Greece" },
        new CountryCode() { Id = 89, Code = "GS", Description = "S. Georgia and S. Sandwich Islands" },
        new CountryCode() { Id = 90, Code = "GT", Description = "Guatemala" },
        new CountryCode() { Id = 91, Code = "GU", Description = "Guam" },
        new CountryCode() { Id = 92, Code = "GW", Description = "Guinea-Bissau" },
        new CountryCode() { Id = 93, Code = "GY", Description = "Guyana" },
        new CountryCode() { Id = 94, Code = "HK", Description = "Hong Kong" },
        new CountryCode() { Id = 95, Code = "HM", Description = "Heard Island and McDonald Islands" },
        new CountryCode() { Id = 96, Code = "HN", Description = "Honduras" },
        new CountryCode() { Id = 97, Code = "HR", Description = "Croatia (Hrvatska)" },
        new CountryCode() { Id = 98, Code = "HT", Description = "Haiti" },
        new CountryCode() { Id = 99, Code = "HU", Description = "Hungary" },
        new CountryCode() { Id = 100, Code = "ID", Description = "Indonesia" },
        new CountryCode() { Id = 101, Code = "IE", Description = "Ireland" },
        new CountryCode() { Id = 102, Code = "IL", Description = "Israel" },
        new CountryCode() { Id = 103, Code = "IN", Description = "India" },
        new CountryCode() { Id = 104, Code = "IO", Description = "British Indian Ocean Territory" },
        new CountryCode() { Id = 105, Code = "IQ", Description = "Iraq" },
        new CountryCode() { Id = 106, Code = "IR", Description = "Iran" },
        new CountryCode() { Id = 107, Code = "IT", Description = "Italy" },
        new CountryCode() { Id = 108, Code = "JM", Description = "Jamaica" },
        new CountryCode() { Id = 109, Code = "JO", Description = "Jordan" },
        new CountryCode() { Id = 110, Code = "JP", Description = "Japan" },
        new CountryCode() { Id = 111, Code = "KE", Description = "Kenya" },
        new CountryCode() { Id = 112, Code = "KG", Description = "Kyrgyzstan" },
        new CountryCode() { Id = 113, Code = "KH", Description = "Cambodia" },
        new CountryCode() { Id = 114, Code = "KI", Description = "Kiribati" },
        new CountryCode() { Id = 115, Code = "KM", Description = "Comoros" },
        new CountryCode() { Id = 116, Code = "KN", Description = "Saint Kitts and Nevis" },
        new CountryCode() { Id = 117, Code = "KP", Description = "Korea (North)" },
        new CountryCode() { Id = 118, Code = "KR", Description = "Korea (South)" },
        new CountryCode() { Id = 119, Code = "KW", Description = "Kuwait" },
        new CountryCode() { Id = 120, Code = "KY", Description = "Cayman Islands" },
        new CountryCode() { Id = 121, Code = "KZ", Description = "Kazakhstan" },
        new CountryCode() { Id = 122, Code = "LA", Description = "Laos" },
        new CountryCode() { Id = 123, Code = "LB", Description = "Lebanon" },
        new CountryCode() { Id = 124, Code = "LC", Description = "Saint Lucia" },
        new CountryCode() { Id = 125, Code = "LI", Description = "Liechtenstein" },
        new CountryCode() { Id = 126, Code = "LK", Description = "Sri Lanka" },
        new CountryCode() { Id = 127, Code = "LR", Description = "Liberia" },
        new CountryCode() { Id = 128, Code = "LS", Description = "Lesotho" },
        new CountryCode() { Id = 129, Code = "LT", Description = "Lithuania" },
        new CountryCode() { Id = 130, Code = "LU", Description = "Luxembourg" },
        new CountryCode() { Id = 131, Code = "LV", Description = "Latvia" },
        new CountryCode() { Id = 132, Code = "LY", Description = "Libya" },
        new CountryCode() { Id = 133, Code = "MA", Description = "Morocco" },
        new CountryCode() { Id = 134, Code = "MC", Description = "Monaco" },
        new CountryCode() { Id = 135, Code = "MD", Description = "Moldova" },
        new CountryCode() { Id = 136, Code = "MG", Description = "Madagascar" },
        new CountryCode() { Id = 137, Code = "MH", Description = "Marshall Islands" },
        new CountryCode() { Id = 138, Code = "MK", Description = "Macedonia" },
        new CountryCode() { Id = 139, Code = "ML", Description = "Mali" },
        new CountryCode() { Id = 140, Code = "MM", Description = "Myanmar" },
        new CountryCode() { Id = 141, Code = "MN", Description = "Mongolia" },
        new CountryCode() { Id = 142, Code = "MO", Description = "Macao" },
        new CountryCode() { Id = 143, Code = "MP", Description = "Northern Mariana Islands" },
        new CountryCode() { Id = 144, Code = "MQ", Description = "Martinique" },
        new CountryCode() { Id = 145, Code = "MR", Description = "Mauritania" },
        new CountryCode() { Id = 146, Code = "MS", Description = "Montserrat" },
        new CountryCode() { Id = 147, Code = "MT", Description = "Malta" },
        new CountryCode() { Id = 148, Code = "MU", Description = "Mauritius" },
        new CountryCode() { Id = 149, Code = "MV", Description = "Maldives" },
        new CountryCode() { Id = 150, Code = "MW", Description = "Malawi" },
        new CountryCode() { Id = 151, Code = "MX", Description = "Mexico" },
        new CountryCode() { Id = 152, Code = "MY", Description = "Malaysia" },
        new CountryCode() { Id = 153, Code = "MZ", Description = "Mozambique" },
        new CountryCode() { Id = 154, Code = "NA", Description = "Namibia" },
        new CountryCode() { Id = 155, Code = "NC", Description = "New Caledonia" },
        new CountryCode() { Id = 156, Code = "NE", Description = "Niger" },
        new CountryCode() { Id = 157, Code = "NF", Description = "Norfolk Island" },
        new CountryCode() { Id = 158, Code = "NG", Description = "Nigeria" },
        new CountryCode() { Id = 159, Code = "NI", Description = "Nicaragua" },
        new CountryCode() { Id = 160, Code = "NL", Description = "Netherlands" },
        new CountryCode() { Id = 161, Code = "NO", Description = "Norway" },
        new CountryCode() { Id = 162, Code = "NP", Description = "Nepal" },
        new CountryCode() { Id = 163, Code = "NR", Description = "Nauru" },
        new CountryCode() { Id = 164, Code = "NU", Description = "Niue" },
        new CountryCode() { Id = 165, Code = "NZ", Description = "New Zealand (Aotearoa)" },
        new CountryCode() { Id = 166, Code = "OM", Description = "Oman" },
        new CountryCode() { Id = 167, Code = "PA", Description = "Panama" },
        new CountryCode() { Id = 168, Code = "PE", Description = "Peru" },
        new CountryCode() { Id = 169, Code = "PF", Description = "French Polynesia" },
        new CountryCode() { Id = 170, Code = "PG", Description = "Papua New Guinea" },
        new CountryCode() { Id = 171, Code = "PH", Description = "Philippines" },
        new CountryCode() { Id = 172, Code = "PK", Description = "Pakistan" },
        new CountryCode() { Id = 173, Code = "PL", Description = "Poland" },
        new CountryCode() { Id = 174, Code = "PM", Description = "Saint Pierre and Miquelon" },
        new CountryCode() { Id = 175, Code = "PN", Description = "Pitcairn" },
        new CountryCode() { Id = 176, Code = "PR", Description = "Puerto Rico" },
        new CountryCode() { Id = 177, Code = "PS", Description = "Palestinian Territory" },
        new CountryCode() { Id = 178, Code = "PT", Description = "Portugal" },
        new CountryCode() { Id = 179, Code = "PW", Description = "Palau" },
        new CountryCode() { Id = 180, Code = "PY", Description = "Paraguay" },
        new CountryCode() { Id = 181, Code = "QA", Description = "Qatar" },
        new CountryCode() { Id = 182, Code = "RE", Description = "Reunion" },
        new CountryCode() { Id = 183, Code = "RO", Description = "Romania" },
        new CountryCode() { Id = 184, Code = "RU", Description = "Russian Federation" },
        new CountryCode() { Id = 185, Code = "RW", Description = "Rwanda" },
        new CountryCode() { Id = 186, Code = "SA", Description = "Saudi Arabia" },
        new CountryCode() { Id = 187, Code = "SB", Description = "Solomon Islands" },
        new CountryCode() { Id = 188, Code = "SC", Description = "Seychelles" },
        new CountryCode() { Id = 189, Code = "SD", Description = "Sudan" },
        new CountryCode() { Id = 190, Code = "SE", Description = "Sweden" },
        new CountryCode() { Id = 191, Code = "SG", Description = "Singapore" },
        new CountryCode() { Id = 192, Code = "SH", Description = "Saint Helena" },
        new CountryCode() { Id = 193, Code = "SI", Description = "Slovenia" },
        new CountryCode() { Id = 194, Code = "SJ", Description = "Svalbard and Jan Mayen" },
        new CountryCode() { Id = 195, Code = "SK", Description = "Slovakia" },
        new CountryCode() { Id = 196, Code = "SL", Description = "Sierra Leone" },
        new CountryCode() { Id = 197, Code = "SM", Description = "San Marino" },
        new CountryCode() { Id = 198, Code = "SN", Description = "Senegal" },
        new CountryCode() { Id = 199, Code = "SO", Description = "Somalia" },
        new CountryCode() { Id = 200, Code = "SR", Description = "Suriname" },
        new CountryCode() { Id = 201, Code = "ST", Description = "Sao Tome and Principe" },
        new CountryCode() { Id = 202, Code = "SU", Description = "USSR (former)" },
        new CountryCode() { Id = 203, Code = "SV", Description = "El Salvador" },
        new CountryCode() { Id = 204, Code = "SY", Description = "Syria" },
        new CountryCode() { Id = 205, Code = "SZ", Description = "Swaziland" },
        new CountryCode() { Id = 206, Code = "TC", Description = "Turks and Caicos Islands" },
        new CountryCode() { Id = 207, Code = "TD", Description = "Chad" },
        new CountryCode() { Id = 208, Code = "TG", Description = "Togo" },
        new CountryCode() { Id = 209, Code = "TH", Description = "Thailand" },
        new CountryCode() { Id = 210, Code = "TJ", Description = "Tajikistan" },
        new CountryCode() { Id = 211, Code = "TK", Description = "Tokelau" },
        new CountryCode() { Id = 212, Code = "TL", Description = "Timor-Leste" },
        new CountryCode() { Id = 213, Code = "TM", Description = "Turkmenistan" },
        new CountryCode() { Id = 214, Code = "TN", Description = "Tunisia" },
        new CountryCode() { Id = 215, Code = "TO", Description = "Tonga" },
        new CountryCode() { Id = 216, Code = "TP", Description = "East Timor" },
        new CountryCode() { Id = 217, Code = "TR", Description = "Turkey" },
        new CountryCode() { Id = 218, Code = "TT", Description = "Trinidad and Tobago" },
        new CountryCode() { Id = 219, Code = "TV", Description = "Tuvalu" },
        new CountryCode() { Id = 220, Code = "TW", Description = "Taiwan" },
        new CountryCode() { Id = 221, Code = "TZ", Description = "Tanzania" },
        new CountryCode() { Id = 222, Code = "UA", Description = "Ukraine" },
        new CountryCode() { Id = 223, Code = "UG", Description = "Uganda" },
        new CountryCode() { Id = 224, Code = "UK", Description = "United Kingdom" },
        new CountryCode() { Id = 225, Code = "UM", Description = "United States Minor Outlying Islands" },
        new CountryCode() { Id = 226, Code = "US", Description = "United States" },
        new CountryCode() { Id = 227, Code = "UY", Description = "Uruguay" },
        new CountryCode() { Id = 228, Code = "UZ", Description = "Uzbekistan" },
        new CountryCode() { Id = 229, Code = "VA", Description = "Vatican City State" },
        new CountryCode() { Id = 230, Code = "VC", Description = "Saint Vincent and the Grenadines" },
        new CountryCode() { Id = 231, Code = "VE", Description = "Venezuela" },
        new CountryCode() { Id = 232, Code = "VG", Description = "Virgin Islands (British)" },
        new CountryCode() { Id = 233, Code = "VI", Description = "Virgin Islands (U.S.)" },
        new CountryCode() { Id = 234, Code = "VN", Description = "Viet Nam" },
        new CountryCode() { Id = 235, Code = "VU", Description = "Vanuatu" },
        new CountryCode() { Id = 236, Code = "WF", Description = "Wallis and Futuna" },
        new CountryCode() { Id = 237, Code = "WS", Description = "Samoa" },
        new CountryCode() { Id = 238, Code = "YE", Description = "Yemen" },
        new CountryCode() { Id = 239, Code = "YT", Description = "Mayotte" },
        new CountryCode() { Id = 240, Code = "YU", Description = "Yugoslavia (former)" },
        new CountryCode() { Id = 241, Code = "ZA", Description = "South Africa" },
        new CountryCode() { Id = 242, Code = "ZM", Description = "Zambia" },
        new CountryCode() { Id = 243, Code = "ZR", Description = "Zaire (former)" },
        new CountryCode() { Id = 244, Code = "ZW", Description = "Zimbabwe" }
    });


   }

}